### ISSUE TITLE
Login / Signup Change Password Requirement Length to 6

### ISSUE THREAD

**Issue by doanja** [doanja/Stock-Tracker#49]

**Comment by miserablepop** [comment]
i will work on this once my last merge requests are approved.

**Comment by miserablepop** [comment]
As of right now, it appears that form validation does not work within a modal. I am still investigating and should hopefully have a definitive answer this afternoon.

**Comment by miserablepop** [comment]
Fixed: updated Modal to use <Form.Input /> rather than <Form.Field><input></input></Form.Field>
